import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="font-sans grid grid-rows-[auto_1fr_auto] min-h-screen">
                    <Navbar />

                    {/* Main content */}
                    <main className="flex flex-col items-center justify-center p-8 sm:p-20">
                        {children}
                    </main>

                    <Footer />
                </div>
            </body>
        </html>
    );
}
